apiVersion: v1
kind: Service
metadata:
  name: ghostfolio
  labels: {{ include "ghostfolio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.ghostfolio.port }}
      protocol: TCP
      name: ghostfolio-http
  selector:
    app: ghostfolio
